import os

# Stock configuration
NIFTY_100_SYMBOLS = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "BPCL.NS",
    "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ICICIGI.NS",
    "ICICIPRULI.NS", "INDUSINDBK.NS", "INFY.NS", "ITC.NS", "JSWSTEEL.NS",
    "KOTAKBANK.NS", "LT.NS", "LTIM.NS", "M&M.NS", "MARUTI.NS",
    "NESTLEIND.NS", "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS",
    "SBILIFE.NS", "SBIN.NS", "SUNPHARMA.NS", "TATACONSUM.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "TCS.NS", "TECHM.NS", "TITAN.NS", "ULTRACEMCO.NS",
    "UPL.NS", "WIPRO.NS", "DLF.NS", "SHRIRAMFIN.NS", "CHOLAFIN.NS",
    "BAJAJHLDNG.NS", "JINDALSTEL.NS", "RECLTD.NS", "ETERNAL.NS", "PFC.NS",
    "LODHA.NS", "SWIGGY.NS", "JIOFIN.NS", "ADANIPOWER.NS", "VBL.NS",
    "BANKBARODA.NS", "PNB.NS", "MOTHERSON.NS", "DMART.NS", "SIEMENS.NS",
    "TATAPOWER.NS", "JSWENERGY.NS", "ADANIGREEN.NS", "NAUKRI.NS", "ABB.NS",
    "TRENT.NS", "HAVELLS.NS", "IOC.NS", "SHREECEM.NS", "TVSMOTOR.NS",
    "TECHM.NS", "AMBUJACEM.NS", "VEDL.NS", "BOSCHLTD.NS", "INDHOTEL.NS",
    "GAIL.NS", "SBILIFE.NS", "GODREJCP.NS", "IRFC.NS", "ZYDUSLIFE.NS",
    "CANBK.NS", "BEL.NS", "DABUR.NS", "HAL.NS", "CGPOWER.NS",
    
    "ABSLPSE.NS", "ALPHA.NS", "ALPHAETF.NS", "ALPL30IETF.NS", "AUTOIETF.NS",
    "BANKBEES.NS", "BANKIETF.NS", "BFSI.NS", "CPSEETF.NS", "EQUAL200.NS",
    "EVINDIA.NS", "FINIETF.NS", "FMCGIETF.NS", "GOLDBEES.NS", "HDFCSML250.NS",
    "HEALTHY.NS", "HNGSNGBEES.NS", "ICICIB22.NS", "ITBEES.NS", "LOWVOLIETF.NS",
    "MAFANG.NS", "MAHKTECH.NS", "MASPTOP50.NS", "METAL.NS", "METALIETF.NS",
    "MID150BEES.NS", "MIDCAPETF.NS", "MIDCAPIETF.NS", "MIDSELIETF.NS", "MIDSMALL.NS",
    "MODEFENCE.NS", "MOM100.NS", "MOM30IETF.NS", "MOMENTUM50.NS", "MON100.NS",
    "MONIFTY500.NS", "MONQ50.NS", "MOSMALL250.NS", "MULTICAP.NS", "NEXT50IETF.NS",
    "NIFTYBEES.NS", "NIFTYIETF.NS", "NV20IETF.NS", "OILIETF.NS", "PHARMABEES.NS",
    "PSUBNKBEES.NS", "PVTBANIETF.NS", "SETFNIF50.NS", "SILVERBEES.NS", "SMALLCAP.NS",
    "TOP100CASE.NS", "TOP10ADD.NS", "JUNIORBEES.NS"
]

# Technical indicator parameters
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
RSI_PERIOD = 14
MFI_PERIOD = 14
VOLUME_MA_SHORT = 20
VOLUME_MA_LONG = 50

# Data configuration
DATA_FOLDER = "stock_data"
TIMEFRAME = "4h"
HISTORICAL_PERIOD = "6mo"  # 6 months of historical data

# Email configuration
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587

# API rate limiting
REQUEST_DELAY = 0.5  # seconds between requests
BATCH_SIZE = 10  # number of stocks to process in each batch

# Dashboard configuration
REFRESH_INTERVAL = 60  # seconds
MAX_CHARTS_PER_PAGE = 6

# Environment variables
EMAIL_USER = os.getenv("EMAIL_USER", "")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
EMAIL_RECIPIENTS = os.getenv("EMAIL_RECIPIENTS", "").split(",") if os.getenv("EMAIL_RECIPIENTS") else []
